export interface User {
    id?: number;      // Optional if auto-generated by the back-end
    username: string;
    password: string;
    mail?: string;
    // Add any other fields based on your Player entity in the back-end
  }
  export interface Character {
    id?: number;
    charName: string;
    charClass: string;
    charLevel: string;
  }
  export interface GameSession {
    id?: number;
    sessionDate: string;
  }
  export interface Inventory {
    id?: number;
    item: string;
  }
  export interface Stats {
    id?: number;
    charStrength: number;
    charDexterity: number;
    charConstitution: number;
    charWisdom: number;
    charCharisma: number;
  }